Repository luckylwk/hoppin-design-system, pull requests merged in 2019-12, with the labels that each got.

#16 User Navigation Bar
  Makefile
  es/components/Image/Avatar.js
  es/components/Image/Tile.js
  es/components/Image/index.js
  es/components/Logo/Logo.js
  es/components/Navigation/Menu.js
  es/components/Navigation/Navigation.js
  es/components/Navigation/NavigationBar.js
  es/components/Navigation/NavigationUser.js
  es/components/Navigation/index.js
  es/index.js
  lib/components/Image/Avatar.js
  lib/components/Image/Tile.js
  lib/components/Image/index.js
  lib/components/Logo/Logo.js
  lib/components/Navigation/Navigation.js
  lib/components/Navigation/NavigationBar.js
  lib/components/Navigation/NavigationUser.js
  lib/components/Navigation/index.js
  lib/index.js
  package.json
  src/components/Image/Avatar.js
  src/components/Image/Readme.mdx
  src/components/Image/Tile.js
  src/components/Image/index.js
  src/components/Logo/Logo.js
  src/components/Navigation/Menu.js
  src/components/Navigation/Navigation.js
  src/components/Navigation/NavigationBar.js
  src/components/Navigation/NavigationUser.js
  src/components/Navigation/Readme.mdx
  src/components/Navigation/index.js
  src/index.js
  yarn.lock
Labels: enhancement

#17 fix: Fields / async-select should trigger onChange
  es/components/Form/Fields.js
  es/components/Form/FieldsSortable.js
  es/components/SteppedForm/StepForm.js
  es/components/SteppedForm/SteppedForm.js
  lib/components/Form/Fields.js
  lib/components/Form/FieldsSortable.js
  lib/components/SteppedForm/StepForm.js
  lib/components/SteppedForm/SteppedForm.js
  package.json
  src/components/Form/Fields.js
  src/components/Form/FieldsSortable.js
  src/components/SteppedForm/StepForm.js
  src/components/SteppedForm/SteppedForm.js
Labels: bug

#18 Exporting styled from styled-components.
  es/components/Loader/BounceLoader.js
  es/components/Loader/CircleLoader.js
  es/components/Loader/HeartLoader.js
  es/components/Loader/Loader.js
  es/components/Loader/index.js
  es/index.js
  lib/components/Loader/BounceLoader.js
  lib/components/Loader/CircleLoader.js
  lib/components/Loader/HeartLoader.js
  lib/components/Loader/Loader.js
  lib/components/Loader/index.js
  lib/index.js
  package.json
  src/components/Loader/BounceLoader.js
  src/components/Loader/CircleLoader.js
  src/components/Loader/HeartLoader.js
  src/components/Loader/Loader.js
  src/components/Loader/Readme.mdx
  src/components/Loader/index.js
  src/index.js
Labels: enhancement

#19 Loading Tile - v0.4.16
  Makefile
  es/components/Loader/Skeleton.js
  es/components/Loader/index.js
  lib/components/Loader/Skeleton.js
  lib/components/Loader/index.js
  package.json
  src/components/Loader/Readme.mdx
  src/components/Loader/Skeleton.js
  src/components/Loader/index.js
Labels: enhancement

#22 Overlay component
  es/components/Loader/BounceLoader.js
  es/components/Loader/CircleLoader.js
  es/components/Loader/HeartLoader.js
  es/components/Loader/Loader.js
  es/components/Loader/Skeleton.js
  es/components/Navigation/Menu.js
  es/components/Navigation/Navigation.js
  es/components/Navigation/NavigationBar.js
  es/components/Navigation/NavigationUser.js
  es/components/Overlay/Overlay.js
  es/components/Overlay/index.js
  lib/components/Loader/BounceLoader.js
  lib/components/Loader/CircleLoader.js
  lib/components/Loader/HeartLoader.js
  lib/components/Loader/Loader.js
  lib/components/Loader/Skeleton.js
  lib/components/Navigation/Menu.js
  lib/components/Navigation/Navigation.js
  lib/components/Navigation/NavigationBar.js
  lib/components/Navigation/NavigationUser.js
  lib/components/Overlay/Overlay.js
  lib/components/Overlay/index.js
  package.json
  src/components/Loader/BounceLoader.js
  src/components/Loader/CircleLoader.js
  src/components/Loader/HeartLoader.js
  src/components/Loader/Loader.js
  src/components/Loader/Skeleton.js
  src/components/Logo/Readme.mdx
  src/components/Navigation/Menu.js
  src/components/Navigation/Navigation.js
  src/components/Navigation/NavigationBar.js
  src/components/Navigation/NavigationUser.js
  src/components/Overlay/Overlay.js
  src/components/Overlay/Readme.mdx
  src/components/Overlay/index.js
Labels: enhancement

#24 Checkbox / RangeSlider
  es/components/Form/Calendar.js
  es/components/Form/Checkbox.js
  es/components/Form/Errors.js
  es/components/Form/Fields.js
  es/components/Form/FieldsSortable.js
  es/components/Form/Input.js
  es/components/Form/Label.js
  es/components/Form/RangeSlider.js
  es/components/Form/SelectStyling.js
  es/components/Form/index.js
  es/components/Image/Avatar.js
  es/components/Navigation/Navigation.js
  es/components/Overlay/Overlay.js
  lib/components/Form/Calendar.js
  lib/components/Form/Checkbox.js
  lib/components/Form/Errors.js
  lib/components/Form/Fields.js
  lib/components/Form/FieldsSortable.js
  lib/components/Form/Input.js
  lib/components/Form/Label.js
  lib/components/Form/RangeSlider.js
  lib/components/Form/SelectStyling.js
  lib/components/Form/index.js
  lib/components/Image/Avatar.js
  lib/components/Navigation/Navigation.js
  lib/components/Overlay/Overlay.js
  package.json
  src/components/Form/Calendar.js
  src/components/Form/Checkbox.js
  src/components/Form/Errors.js
  src/components/Form/Fields.js
  src/components/Form/FieldsSortable.js
  src/components/Form/Input.js
  src/components/Form/Label.js
  src/components/Form/RangeSlider.js
  src/components/Form/Readme.mdx
  src/components/Form/SelectStyling.js
  src/components/Form/index.js
  src/components/Image/Avatar.js
  src/components/Loader/Skeleton.js
  src/components/Navigation/Navigation.js
  src/components/Overlay/Overlay.js
  yarn.lock
Labels: bug, enhancement

#25 TextareaMd Docz update
  es/components/Expandable/Expandable.js
  es/components/Form/Fields.js
  es/components/Form/RangeSlider.js
  es/components/Form/TextareaMd/index.js
  lib/components/Expandable/Expandable.js
  lib/components/Form/Fields.js
  lib/components/Form/RangeSlider.js
  lib/components/Form/TextareaMd/index.js
  src/components/Expandable/Expandable.js
  src/components/Form/Fields.js
  src/components/Form/RangeSlider.js
  src/components/Form/Readme.mdx
  src/components/Form/TextareaMd/index.js
Labels: enhancement
